### ISSUE TITLE
Crash on app start

### ISSUE THREAD

**Issue by mmoczkowski** [lokalise/lokalise-android-sdk#1]
Hi,

I'm attempting to integrate Lokalise SDK into my app. Below is my application class. As you can see, it's fairly simple. Besides Lokalise, there's Dagger, Multidex and Fabric stuff.

    @Override
    public void onCreate() {
        super.onCreate();
        
        LokaliseSDK.init(BuildConfig.LOKALISE_API_TOKEN, BuildConfig.LOKALISE_PROJECT_ID, this);
        LokaliseSDK.setPreRelease(BuildConfig.DEBUG);
        LokaliseSDK.updateTranslations();
        
        TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
        Fabric.with(this, new Crashlytics(), new TwitterCore(authConfig), new Digits.Builder().withTheme(R.style.CustomDigitsTheme).build());
    }

    public ApplicationComponent getComponent() {
        if (mApplicationComponent == null) {
            mApplicationComponent = DaggerApplicationComponent.builder()
                    .applicationModule(new ApplicationModule(this))
                    .build();
        }
        return mApplicationComponent;
    }
    
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(LokaliseContextWrapper.wrap(base));
        MultiDex.install(this);
    }

This however, gives me the following exception:

`java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: co.lokalise.android.sdk.exceptions.LokaliseInitException: Lokalise SDK was not initialised! Please call LokaliseSDK.init(<apiKey>, <projectId>) first.
                                                                                at android.app.ActivityThread.installProvider(ActivityThread.java:5856)
                                                                                at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
                                                                                at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                             Caused by: co.lokalise.android.sdk.exceptions.LokaliseInitException: Lokalise SDK was not initialised! Please call LokaliseSDK.init(<apiKey>, <projectId>) first.
                                                                                at co.lokalise.android.sdk.LokaliseSDK.getInstance(LokaliseSDK.java:110)
                                                                                at co.lokalise.android.sdk.LokaliseResources.<init>(LokaliseResources.java:46)
                                                                                at co.lokalise.android.sdk.core.LokaliseContextWrapper.getResources(LokaliseContextWrapper.java:74)
                                                                                at android.content.ContextWrapper.getResources(ContextWrapper.java:86)
                                                                                at com.google.android.gms.common.internal.zzam.<init>(Unknown Source)
                                                                                at com.google.firebase.FirebaseOptions.fromResource(Unknown Source)
                                                                                at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
                                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
                                                                                at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                at android.app.ActivityThread.installProvider(ActivityThread.java:5853)
                                                                                at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445) 
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384) 
                                                                                at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

**Comment by DrParanoia** [comment]
Will look into it. Thanks for the report!
