### ISSUE TITLE
StrictMode policy violations

### ISSUE THREAD

**Issue by denlig** [lokalise/lokalise-android-sdk#7]
I have StrictMode enabled (with defaults) when running my app in debug, and I'm noticing a lot of policy violations every time Lokalise is fetching strings:

`D/StrictMode: StrictMode policy violation; ~duration=56 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
                                                                             at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
                                                                             at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1042)
                                                                             at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
                                                                             at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
                                                                             at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                             at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                                             at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                                             at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
                                                                             at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
                                                                             at co.lokalise.android.sdk.core.LokaliseDBHelper.getTranslation(LokaliseDBHelper.java:243)
                                                                             at co.lokalise.android.sdk.core.LokaliseDBHelper.getTranslation(LokaliseDBHelper.java:256)
                                                                             at co.lokalise.android.sdk.LokaliseResourcesHelper.getText(LokaliseResourcesHelper.java:81)
                                                                             at co.lokalise.android.sdk.LokaliseResourcesHelper.getString(LokaliseResourcesHelper.java:36)
                                                                             at co.lokalise.android.sdk.LokaliseResourcesHelper.getString(LokaliseResourcesHelper.java:41)
                                                                             at co.lokalise.android.sdk.LokaliseResources.getString(LokaliseResources.java:37)`

Using the newest SDK.

**Comment by DrParanoia** [comment]
So, it looks like StrictMode does not like LokaliseSDK accessing the DB on the main thread.

The thing is, that this process should be synchronous, since translations are needed immediately when you call getString for example, or inflate an XML layout

In the future, we might migrate from Androids SQLite to a better/faster solution, but currently there is not much we can fix.
